spring.application.name=Spring-Sec-Demo
spring.security.user.name=bose
spring.security.user.password=1234

server.servlet.session.cookie.same-site=strict

spring.datasource.url=jdbc:postgresql://localhost:5432/telusko
spring.datasource.username=postgres
spring.datasource.password=1234567890

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update